name: Build

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', 'highest']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"

      - run: "composer run check-syntax"
      - run: "composer run check-codestyle"
      - run: "composer run static-analysis"
      - run: "composer run test"
